In [2]:
# Import numpy
import numpy as np

# Numpy Basics 

[The Documentation](https://numpy.org/doc/stable/user/)

In [3]:
# This is 1D array
my_1d_array = np.array([1, 2, 3])  # [1, 2, 3] is a python list
my_1d_array

array([1, 2, 3])

In [4]:
# We can do 2D arrays from nested python lists
my_2d_array = np.array([[1, 2], [3, 4]])
my_2d_array

array([[1, 2],
       [3, 4]])

In [5]:
# Other ways to create arrays using numpy!
n = 3 # Number of elements
np.zeros(n)

array([0., 0., 0.])

In [6]:
np.zeros(n)

array([0., 0., 0.])

In [7]:
np.arange(n)

array([0, 1, 2])

In [8]:
arr = np.array([[1, 2], [3, 4]])

In [9]:
ndim = arr.ndim
size = arr.size
r, c = arr.shape
# Note that we are not using (). 

print(f"The array `arr` has {ndim} dimensions. It has a total of {size} elements, {r} rows and {c} columns.")

The array `arr` has 2 dimensions. It has a total of 4 elements, 2 rows and 2 columns.


In [10]:
# We will try with a bigger array!
arr = np.arange(6)

In [11]:
# Basic indexing
arr[0], arr[-1], arr[[1, 3, 4]]

(0, 5, array([1, 3, 4]))

In [12]:
# Slicing
arr[1:], arr[:-2], arr[1:-2]

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3]), array([1, 2, 3]))

In [13]:
# Mash indexing
greater_than_1 = arr > 1 # Compare the array to 1
print(f"The mask is: {greater_than_1}")

# And we index using the mask
arr[greater_than_1]

The mask is: [False False  True  True  True  True]


array([2, 3, 4, 5])

In [18]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Basic indexing
arr[1, 0], arr[-1, -2], arr[[1, -1], [0, -2]]

(3, 5, array([3, 5]))

In [19]:
# We can also use masks
greater_than_1 = arr > 1
arr[greater_than_1]

array([2, 3, 4, 5, 6])

In [20]:
# Slicing

arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[1:, ], arr[:, :-1]

(array([[3, 4],
        [5, 6]]),
 array([[1],
        [3],
        [5]]))

In [26]:
# Using a bigger array: 
arr = np.arange(1, 25).reshape(4, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [24]:
arr[:3, 1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]])

In [25]:
arr[:-2, 3:]

array([[ 4,  5,  6],
       [10, 11, 12]])

##### 📚 Homework! :)

1. Can you find on the docs a way to change the dimensions of an array?  
*Hint: we want to change its shape.*

2. Create the following arrays: 
    - Array that has same dimmensions as `my_2d_array` but filled with only ones. That is an ones array *like* `my_2d_array`.
    - An array that the initial value is 3 and the end value is 10 with 8 *equaly spaced values*. 
    - A 3x3 diagonal matrix.

3. Can you select only the rows (in 2d) if the second value of the row is > 10?

Use the DOCS!

